services:
  # Web Service
  - type: web
    name: extractme
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn marksheet_project.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: extractme-db
          property: connectionString

# Database
databases:
  - name: extractme-db
    databaseName: extractme
    plan: free
